### Première vue :

In [59]:
import pandas as pd

# Récupération du dataset
path = "https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz"
df = pd.read_csv(path, nrows=10000, sep='\t',  encoding="utf-8", low_memory = False, na_filter = True )     
df

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,glycemic-index_100g,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g
0,54,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1582569031,2020-02-24T18:30:31Z,1733085204,2024-12-01T20:33:24Z,NaN,1740205422,2025-02-22T06:23:42Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1673620307,2023-01-13T14:31:47Z,1739902555,2025-02-18T18:15:55Z,waistline-app,1740360377,2025-02-24T01:26:17Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,114,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1580066482,2020-01-26T19:21:22Z,1737247862,2025-01-19T00:51:02Z,smoothie-app,1740075018,2025-02-20T18:10:18Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,http://world-en.openfoodfacts.org/product/0000...,inf,1634745456,2021-10-20T15:57:36Z,1740924602,2025-03-02T14:10:02Z,smoothie-app,1740924602,2025-03-02T14:10:02Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1572117743,2019-10-26T19:22:23Z,1738073570,2025-01-28T14:12:50Z,NaN,1740085032,2025-02-20T20:57:12Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15899,http://world-en.openfoodfacts.org/product/0001...,macrofactor,1740049723,2025-02-20T11:08:43Z,1740049730,2025-02-20T11:08:50Z,macrofactor,1740049730,2025-02-20T11:08:50Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,1590000211,http://world-en.openfoodfacts.org/product/0001...,omnomnotes-app,1673311705,2023-01-10T00:48:25Z,1673312282,2023-01-10T00:58:02Z,omnomnotes-app,1707874424,2024-02-14T01:33:44Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,1590006450,http://world-en.openfoodfacts.org/product/0001...,usda-ndb-import,1489090355,2017-03-09T20:12:35Z,1728036862,2024-10-04T10:14:22Z,fix-code-bot,1728036862,2024-10-04T10:14:22Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,1590006978,http://world-en.openfoodfacts.org/product/0001...,smoothie-app,1727305008,2024-09-25T22:56:48Z,1728043141,2024-10-04T11:59:01Z,fix-code-bot,1738847008,2025-02-06T13:03:28Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999,1590013401,http://world-en.openfoodfacts.org/product/0001...,foodvisor,1704235740,2024-01-02T22:49:00Z,1728043142,2024-10-04T11:59:02Z,fix-code-bot,1738847008,2025-02-06T13:03:28Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df_to_clean = df 
df_to_clean.info() 
df_to_clean.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 199 entries, last_modified_by to acidity_100g
dtypes: float64(131), int64(1), object(67)
memory usage: 15.2+ MB

,last_updated_t,cities,allergens_en,serving_quantity,additives_n,additives,nutriscore_score,nova_group,environmental_score_score,product_quantity,...,glycemic-index_100g,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g
count,1.000000e+04,0.0,0.0,3062.000000,1704.000000,0.0,1275.000000,1398.000000,696.000000,2241.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,1.734791e+09,NaN,NaN,124.460211,1.860329,NaN,11.289412,3.231044,53.454023,476.290285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,7.520425e+06,NaN,NaN,529.820139,2.778235,NaN,11.183225,1.148393,26.923727,1251.920002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.707490e+09,NaN,NaN,0.000000,0.000000,NaN,-17.000000,1.000000,-20.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.728057e+09,NaN,NaN,25.000000,0.000000,NaN,1.000000,3.000000,35.000000,50.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.738819e+09,NaN,NaN,50.500000,1.000000,NaN,12.000000,4.000000,55.000000,230.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.740183e+09,NaN,NaN,130.000000,3.000000,NaN,19.000000,4.000000,74.000000,500.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.740968e+09,NaN,NaN,28000.000000,19.000000,NaN,50.000000,4.000000,123.000000,30000.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
# Sélection des colonnes numériques
num_cols =df_to_clean.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(f"Colonnes numériques détectées : {num_cols}")

Colonnes numériques détectées : ['last_updated_t', 'cities', 'allergens_en', 'serving_quantity', 'additives_n', 'additives', 'nutriscore_score', 'nova_group', 'environmental_score_score', 'product_quantity', 'unique_scans_n', 'completeness', 'last_image_t', 'energy-kj_100g', 'energy-kcal_100g', 'energy_100g', 'energy-from-fat_100g', 'fat_100g', 'saturated-fat_100g', 'butyric-acid_100g', 'caproic-acid_100g', 'caprylic-acid_100g', 'capric-acid_100g', 'lauric-acid_100g', 'myristic-acid_100g', 'palmitic-acid_100g', 'stearic-acid_100g', 'arachidic-acid_100g', 'behenic-acid_100g', 'lignoceric-acid_100g', 'cerotic-acid_100g', 'montanic-acid_100g', 'melissic-acid_100g', 'unsaturated-fat_100g', 'monounsaturated-fat_100g', 'omega-9-fat_100g', 'polyunsaturated-fat_100g', 'omega-3-fat_100g', 'omega-6-fat_100g', 'alpha-linolenic-acid_100g', 'eicosapentaenoic-acid_100g', 'docosahexaenoic-acid_100g', 'linoleic-acid_100g', 'arachidonic-acid_100g', 'gamma-linolenic-acid_100g', 'dihomo-gamma-linolenic-acid_100g', 'oleic-acid_100g', 'elaidic-acid_100g', 'gondoic-acid_100g', 'mead-acid_100g', 'erucic-acid_100g', 'nervonic-acid_100g', 'trans-fat_100g', 'cholesterol_100g', 'carbohydrates_100g', 'sugars_100g', 'added-sugars_100g', 'sucrose_100g', 'glucose_100g', 'fructose_100g', 'lactose_100g', 'maltose_100g', 'maltodextrins_100g', 'starch_100g', 'polyols_100g', 'erythritol_100g', 'fiber_100g', 'soluble-fiber_100g', 'insoluble-fiber_100g', 'proteins_100g', 'casein_100g', 'serum-proteins_100g', 'nucleotides_100g', 'salt_100g', 'added-salt_100g', 'sodium_100g', 'alcohol_100g', 'vitamin-a_100g', 'beta-carotene_100g', 'vitamin-d_100g', 'vitamin-e_100g', 'vitamin-k_100g', 'vitamin-c_100g', 'vitamin-b1_100g', 'vitamin-b2_100g', 'vitamin-pp_100g', 'vitamin-b6_100g', 'vitamin-b9_100g', 'folates_100g', 'vitamin-b12_100g', 'biotin_100g', 'pantothenic-acid_100g', 'silica_100g', 'bicarbonate_100g', 'potassium_100g', 'chloride_100g', 'calcium_100g', 'phosphorus_100g', 'iron_100g', 'magnesium_100g', 'zinc_100g', 'copper_100g', 'manganese_100g', 'fluoride_100g', 'selenium_100g', 'chromium_100g', 'molybdenum_100g', 'iodine_100g', 'caffeine_100g', 'taurine_100g', 'ph_100g', 'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-dried_100g', 'fruits-vegetables-nuts-estimate_100g', 'fruits-vegetables-nuts-estimate-from-ingredients_100g', 'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g', 'carbon-footprint_100g', 'carbon-footprint-from-meat-or-fish_100g', 'nutrition-score-fr_100g', 'nutrition-score-uk_100g', 'glycemic-index_100g', 'water-hardness_100g', 'choline_100g', 'phylloquinone_100g', 'beta-glucan_100g', 'inositol_100g', 'carnitine_100g', 'sulphate_100g', 'nitrate_100g', 'acidity_100g']

In [88]:
#Ne pas suup les colonnes en dure mais en optionnel 
# Calcul du pourcentage de valeurs manquantes par colonne
missing_percentage =df_to_clean.isnull().mean() * 100  
print(missing_percentage)

last_modified_by              3.47
last_updated_t                0.00
last_updated_datetime         0.00
product_name                 13.25
abbreviated_product_name     99.94
                             ...
inositol_100g               100.00
carnitine_100g              100.00
sulphate_100g               100.00
nitrate_100g                100.00
acidity_100g                100.00
Length: 199, dtype: float64

In [96]:
#Supprimer les colonnes qui ne servent pas à notre étude 
columns_drop = ['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime' ]

# Suppression des colonnes
df_cleaned =df_to_clean.drop(columns=columns_drop)

# Affichage du DataFrame après suppression
print(df_cleaned)

KeyError: "['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime'] not found in axis"

In [100]:
 # Calcul du pourcentage de valeurs manquantes pour chaque colonne
missing_percentage = df_to_clean.isnull().mean() * 100

# Sélection des colonnes à garder : celles avec moins de 80% de valeurs manquantes
df_cleaned = df.loc[:, missing_percentage <= 90]

# Affichage du DataFrame après suppression
print(df_cleaned)


threshold = 70
columns_to_drop = percent_missing[
    percent_missing.values > threshold].index
columns_to_drop

     last_modified_by  last_updated_t last_updated_datetime  \
0                 NaN      1740205422  2025-02-22T06:23:42Z
1       waistline-app      1740360377  2025-02-24T01:26:17Z
2        smoothie-app      1740075018  2025-02-20T18:10:18Z
3        smoothie-app      1740924602  2025-03-02T14:10:02Z
4                 NaN      1740085032  2025-02-20T20:57:12Z
...               ...             ...                   ...
9995      macrofactor      1740049730  2025-02-20T11:08:50Z
9996   omnomnotes-app      1707874424  2024-02-14T01:33:44Z
9997     fix-code-bot      1728036862  2024-10-04T10:14:22Z
9998     fix-code-bot      1738847008  2025-02-06T13:03:28Z
9999     fix-code-bot      1738847008  2025-02-06T13:03:28Z

                                  product_name quantity          brands  \
0                Limonade artisanale a la rose      NaN             NaN
1     Mozzarella Schnittfest Gerieben 45% Fett      NaN   Gut & Gunstig
2                                Chocolate n 3     80 g  Jeff de Bruges
3                               Poulet fermier     300g      COCO & CO.
4         Paleta gran reserva - Sierra nevada-    750ml        AdvoCare
...                                        ...      ...             ...
9995        Chicken Stir fry With Basmati Rice      NaN     Fitfoods 4u
9996                                   Hot Dog      NaN          Kroger
9997                            Chicken Franks      NaN             NaN
9998                                       NaN      NaN             NaN
9999                            Classic franks    12 oz  Classic franks

         brands_tags                                         categories  \
0                NaN                                                NaN
1        gut-gunstig                                                NaN
2     jeff-de-bruges                                                NaN
3            coco-co                              Supplements, Vegtable
4           advocare        Bebidas y preparaciones de bebidas, Bebidas
...              ...                                                ...
9995     fitfoods-4u                                                NaN
9996          kroger                                                NaN
9997             NaN                                                NaN
9998             NaN                                                NaN
9999  classic-franks  Meats and their products,Meat preparations,Pre...

                                        categories_tags  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                            en:supplements,en:vegtable
4     en:beverages-and-beverages-preparations,en:bev...
...                                                 ...
9995                                                NaN
9996                                                NaN
9997                                                NaN
9998                                                NaN
9999  en:meats-and-their-products,en:meat-preparatio...

                                          categories_en  ... fat_100g  \
0                                                   NaN  ...      NaN
1                                                   NaN  ...    25.00
2                                                   NaN  ...    44.00
3                                  Supplements,Vegtable  ...     6.00
4        Beverages and beverages preparations,Beverages  ...      NaN
...                                                 ...  ...      ...
9995                                                NaN  ...     2.70
9996                                                NaN  ...    21.40
9997                                                NaN  ...    21.43
9998                                                NaN  ...      NaN
9999  Meats and their products,Meat preparations,Pre...  ...    21.40

     saturated-fat_100g carbohydrates_100g sugars_100g fiber_100g  \
0                   NaN                NaN         NaN        NaN
1                17.300               3.00        1.00        NaN
2                28.000              30.00       27.00        NaN
3                 1.000              21.40       11.10        2.0
4                   NaN                NaN         NaN        NaN
...                 ...                ...         ...        ...
9995              0.567              10.70        1.47        1.4
9996              6.250               7.14        3.57        0.0
9997              6.250               8.93        3.57        0.0
9998                NaN                NaN         NaN        NaN
9999              7.140               7.14        4.76        NaN

     proteins_100g salt_100g sodium_100g  \
0              NaN       NaN         NaN
1            23.00   1.20000    0.480000
2             7.10   0.02500    0.010000
3            11.20  11.80000    4.720000
4              NaN       NaN         NaN
...            ...       ...         ...
9995         11.10   0.56200    0.225000
9996          7.14   2.32000    0.929000
9997         10.71   2.67716    1.070864
9998           NaN       NaN         NaN
9999          7.14   2.38000    0.952000

     fruits-vegetables-nuts-estimate-from-ingredients_100g  \
0                                                   NaN
1                                              0.000000
2                                                   NaN
3                                            100.000000
4                                              0.011335
...                                                 ...
9995                                                NaN
9996                                           0.000000
9997                                           0.000000
9998                                                NaN
9999                                                NaN

     nutrition-score-fr_100g
0                        NaN
1                        NaN
2                        NaN
3                       25.0
4                        NaN
...                      ...
9995                     NaN
9996                     NaN
9997                     NaN
9998                     NaN
9999                    22.0

[10000 rows x 61 columns]